apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ollama
  namespace: llm
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        node: gpu
      containers:
      - name: ollama
        image: docker.io/ollama/ollama:0.3.14
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - name: models
            mountPath: /root/.ollama
            mountPropagation: Bidirectional
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        # env:
        # - name: OLLAMA_NUM_PARALLEL
        #   value: "4"
        # - name: OLLAMA_MAX_LOADED_MODELS
        #   value: "2"
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: ollama-pvc
          readOnly: false
