apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: minio
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
    - name: minio
      port: 9000
  selector:
    app: minio