apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio2
  namespace: minio
spec:
  serviceName: minio-headless
  replicas: 1
  selector:
    matchLabels:
      app: minio
      node: kw2
  template:
    metadata:
      labels:
        app: minio
        node: kw2
    spec:
      nodeSelector:
        kubernetes.io/hostname: kw2
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - server
            - --console-address
            - ":9001"
            - http://minio{1...3}-0.minio-headless/data
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              value: "bigred"
            - name: MINIO_ROOT_PASSWORD
              value: "******"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /var/minio
            type: Directory
